# Generated by Django 2.2.9 on 2020-01-23 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nick',
        ),
    ]
