# Generated by Django 2.2.8 on 2020-01-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Less than 1 year'), (2, 'Less than 2 year'), (3, 'Less than 3 year'), (4, 'more than 3 year')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Male'), (2, 'Fremale')], default=0),
        ),
    ]
