# Generated by Django 2.2.8 on 2020-01-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200123_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Unknown', 'U'), ('Male', 'M'), ('Female', 'F')], default='U', max_length=7),
        ),
    ]
